#!/usr/bin/python
import time
import sys

try:
    iface = sys.argv[1]
    interval = float(sys.argv[2])
except:
    sys.exit("Usage: %s <network interface name> <interval seconds>" % __file__)

try:
    rx_stats = open('/sys/class/net/%s/statistics/rx_packets' % iface)
    tx_stats = open('/sys/class/net/%s/statistics/tx_packets' % iface)
except:
    sys.exit("Unable to get stats. Not Linux?")
    
while True:

    ### SEEK NA START
    rx_stats.seek(0,0)
    tx_stats.seek(0,0)

    rx_packets_1 = float(rx_stats.read())
    tx_packets_1 = float(tx_stats.read())

    ### MAL ZASPIMO
    try: time.sleep(interval)
    except KeyboardInterrupt: break
    
    ### SEEK NA START
    rx_stats.seek(0,0)
    tx_stats.seek(0,0)

    rx_packets_2 = int(rx_stats.read())
    tx_packets_2 = int(tx_stats.read())

    ### MAL PORACUNAMO
    rx_pps = (rx_packets_2 - rx_packets_1) / interval
    tx_pps = (tx_packets_2 - tx_packets_1) / interval

    print 'RX: %5d pps | TX: %5d pps' % (rx_pps, tx_pps)

rx_stats.close()
tx_stats.close()
